
header: images/mugshot.jpg

title: Evan Leet

description: Data professional with a backround in health care and psychiatric research
 
  <br><br>
  

google_analytics: UA-000000-0 # your Google Analytics tracking ID here

theme: jekyll-theme-slate
