
logo: images/MUGSHOTJAN2022.jpg

title: Evan Leet

description: Bassist locatged in the Pittsburgh area
 
  <br><br>
  

google_analytics: UA-000000-0 # your Google Analytics tracking ID here

theme: jekyll-theme-minimal
