title: Evan Leet # your name (or website title) here
logo: "https://scontent.fagc1-2.fna.fbcdn.net/v/t1.0-9/p960x960/64585300_648598898991712_6591349772160860160_o.jpg?_nc_cat=111&_nc_eui2=AeHLUU5fsY76yXiY_TYKtarASF5aOObqFOUXPgl6aDp-4HnGKstiiiR5H0NYhQXorBUNw2z4t9V7JVooSC-mEPIZeJqRx3N0w3gNZ47qAfzDng&_nc_oc=AQllRueX9AWCmWpTmaY2tB2A28PNHvxDBYtw39I0MbsXnjQwCUNIKZ7SQ3tlJKkOsQtt9xjgiiRp3ufKEKvQJmmC&_nc_ht=scontent.fagc1-2.fna&oh=3bdcb1692c378f38f72381b2e7a151a4&oe=5E4A9DCC" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'll be graduating shortly with a BS in Data Analytics. I am currently working on little projects here and there to build a portfolio.
 
  <br><br>
  

google_analytics: UA-000000-0 # your Google Analytics tracking ID here

theme: jekyll-theme-slate
